DROP TABLE DokumentPositionen;
DROP TABLE Dokumente;
DROP TABLE Kunden;

-- 1. Tabelle: Kunden
CREATE TABLE Kunden (
    KundenID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    KundenNummer VARCHAR2(50) NOT NULL UNIQUE,
    Name VARCHAR2(150) NOT NULL,
    Adresse VARCHAR2(255) NOT NULL
);

-- 2. Tabelle: Dokumente
CREATE TABLE Dokumente (
    DokumentID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DokumentNummer VARCHAR2(50) NOT NULL UNIQUE,
    Typ VARCHAR2(20) NOT NULL,
    ErstellungsDatum DATE NOT NULL,
    RabattInProzent DECIMAL(5,2) DEFAULT 0.00,
    KundenID INT NOT NULL,
    CONSTRAINT fk_dokument_kunde FOREIGN KEY (KundenID) REFERENCES Kunden(KundenID) ON DELETE CASCADE
);

-- 3. Tabelle: DokumentPositionen
CREATE TABLE DokumentPositionen (
    PositionID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Bezeichnung VARCHAR2(255) NOT NULL,
    Menge DECIMAL(10,2) NOT NULL,
    Einzelpreis DECIMAL(10,2) NOT NULL,
    DokumentID INT NOT NULL,
    CONSTRAINT fk_pos_dokument FOREIGN KEY (DokumentID) REFERENCES Dokumente(DokumentID) ON DELETE CASCADE
);